# Generated by Django 3.0.6 on 2020-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('fileupload', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
